In [1]:
import pandas as pd

In [2]:
s3 = pd.Series([12,-4,7,9,6,48,-3], index=['a','b','c','a','e','f','a'])
print(s3.loc['a'])

a    12
a     9
a    -3
dtype: int64


In [3]:
print(s3.iloc[[0,3,6]])

a    12
a     9
a    -3
dtype: int64


In [4]:
import numpy as np


In [5]:
arr = np.array([1,2,3,4,5,6])
s = pd.Series(arr)
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [6]:
print(arr)
print(s)

[1 2 3 4 5 6]
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [7]:
#Una estructura de datos diferente con la misma region de memoria asignada a los datos 

arr[1] = 500
print(arr)
print(s)

[  1 500   3   4   5   6]
0      1
1    500
2      3
3      4
4      5
5      6
dtype: int64


In [8]:
series2 = pd.Series(arr.copy())
print(series2)

0      1
1    500
2      3
3      4
4      5
5      6
dtype: int64


In [9]:
print(arr)
series2[3] = 200
print(series2)
print(arr)

[  1 500   3   4   5   6]
0      1
1    500
2      3
3    200
4      5
5      6
dtype: int64
[  1 500   3   4   5   6]


In [10]:
s = pd.Series([1,2,3,4,5,6,7,8,9])
print(s>5)
print(s[s>5])

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool
5    6
6    7
7    8
8    9
dtype: int64


In [11]:
s = pd.Series([4,5,6,7,7,9])
print("Division:\n",s/2)
print("Multiplication :\n", s*2)
print("Sum: \n",s + 2)
print("Substraction:\n",s - 2)

Division:
 0    2.0
1    2.5
2    3.0
3    3.5
4    3.5
5    4.5
dtype: float64
Multiplication :
 0     8
1    10
2    12
3    14
4    14
5    18
dtype: int64
Sum: 
 0     6
1     7
2     8
3     9
4     9
5    11
dtype: int64
Substraction:
 0    2
1    3
2    4
3    5
4    5
5    7
dtype: int64


In [12]:
s = pd.Series([1,0,3,4,0,6,7,0,9], index=['white','black','red','blue','green','yellow','purple','orange','pink'])
print(s)
print(s.unique())

white     1
black     0
red       3
blue      4
green     0
yellow    6
purple    7
orange    0
pink      9
dtype: int64
[1 0 3 4 6 7 9]


In [13]:
print(s.value_counts())

0    3
1    1
3    1
4    1
6    1
7    1
9    1
Name: count, dtype: int64


In [15]:
arr = np.array([12,-4,7,9]) ## Pandas es el hijo de numpy
s = pd.Series(arr)
s

0    12
1    -4
2     7
3     9
dtype: int64

In [ ]:
s1 = pd.Series(s)
s[1] = 2234 #s1 y s son lo mismo
s

0      12
1    2234
2       7
3       9
dtype: int64

In [18]:
print(s[s>100]) # imprime los elementos que cumplen la condicion

1    2234
dtype: int64


In [19]:
print(np.log(s))
print(np.sqrt(s))
print(np.sin(s))

0    2.484907
1    7.711549
2    1.945910
3    2.197225
dtype: float64
0     3.464102
1    47.265209
2     2.645751
3     3.000000
dtype: float64
0   -0.536573
1   -0.321794
2    0.656987
3    0.412118
dtype: float64


In [25]:
s = pd.Series([3,2,3,5,5,67], index=['white','black','yellow','red','blue','green'])
s

white      3
black      2
yellow     3
red        5
blue       5
green     67
dtype: int64

In [27]:
s.unique() # imprime los valores unicos

array([ 3,  2,  5, 67])

In [34]:
s.isin([4,3])


white      True
black     False
yellow     True
red       False
blue      False
green     False
dtype: bool

In [35]:
s[s.isin([4,3])]

white     3
yellow    3
dtype: int64

In [36]:
s2 = pd.Series([3,-4,np.nan, 34323])
s2

0        3.0
1       -4.0
2        NaN
3    34323.0
dtype: float64

In [38]:
print(s2.isnull())
print(s2.notnull)

0    False
1    False
2     True
3    False
dtype: bool
<bound method Series.notnull of 0        3.0
1       -4.0
2        NaN
3    34323.0
dtype: float64>


In [39]:
print(s2[s2.isnull()])

2   NaN
dtype: float64


In [43]:
mydict = {'red':30,'blue':900,'true':24}
n = pd.Series(mydict)
n


red      30
blue    900
true     24
dtype: int64

In [45]:
mydict1 = {'red':30,'blue':900,'true':24,'javi':899,'hoy':9}
mydict2 = {'red':30,'blue':900,'true':24,'yo':899,'tu':9}
s1 = pd.Series(mydict1)
s2 = pd.Series(mydict2)

print(s1 + s2)



blue    1800.0
hoy        NaN
javi       NaN
red       60.0
true      48.0
tu         NaN
yo         NaN
dtype: float64


#### Exercise 1

In [46]:
s1 = pd.Series([1,5,2,3,7]).tolist()
s1


[1, 5, 2, 3, 7]

#### Exercise 2
##### Create a pandas series "s" of 10 random decimal values using the numpu random.rand() function. Create a subset series "s1"  that has all the values of "s" that are less than 5. 

In [64]:
s = np.random.randn(10)*9
s2 = s[s<5]
s2

array([ -2.42572161, -13.34737756,  -8.31453036])

#### Exercise 3
wriite a pandas program to add, substract, multiple and divide two pandas series
Sample Series: [2,4,6,8,10], [1,3,5,7,9]

In [66]:
s1 = pd.Series([2,4,6,8,10])
s2 = pd.Series([1,3,5,7,9])
print(s1.add(s2))


0     3
1     7
2    11
3    15
4    19
dtype: int64


#### Exercise 6
write a pandas program to convert a dictionary to a pandas series
Original dictionary: 
{'a':100,'b':200,'c':300,'d':400,'e':800}

In [68]:
s = pd.Series({'a':100,'b':200,'c':300,'d':400,'e':800})
s

a    100
b    200
c    300
d    400
e    800
dtype: int64

#### Exercise 7
write a pandas program to create the minimum, maximum, mean and standard deviation of the following series: [1,2,3,4,5,6,7,8,9,5,3]

In [69]:
s7 = pd.Series([1,2,3,4,5,6,7,8,9,5,3])
print("Minimum:", s7.min())
print("Maximum:", s7.max())
print("Mean:", s7.mean())
print("Standard Deviation:", s7.std())

Minimum: 1
Maximum: 9
Mean: 4.818181818181818
Standard Deviation: 2.522624895547565


#### Exercise 8: 
write a pandas program to get the items of series 1 that are present in series2
sr1 = [1,2,3,4,5]
sr2 = [2,4,6,8,10]


In [70]:
sr1 = [1,2,3,4,5]
sr2 = [2,4,6,8,10]
s1 = pd.Series(sr1)
s2 = pd.Series(sr2)
s1[s1.isin(s2)]

1    2
3    4
dtype: int64

#### Exercise 9
Write a pandas program to get the items of series 1 that are not present in series2.
sr1 = [1,2,3,4,5]
sr2 = [2,4,6,8,10]

In [75]:
sr1 = [1,2,3,4,5]
sr2 = [2,4,6,8,10]
s1 = pd.Series(sr1)
s2 = pd.Series(sr2)
print(s1[~s1.isin(s2)])

0    1
2    3
4    5
dtype: int64


#### Exercise 10
np.random.randint(2,10,size=40) returns a numpy array of 40 integer numbers between 2 and 10. use the above numpy function to generate an array of 150 integer numbers from 10 to 20. Create a pandas series from this array and calculate the frequency counts of each unique value. 

In [ ]:
n = np.random.randint(2,10,size=40)
n1 = np.random.randint(10,20,size=150)
s = pd.Series(n1)
print(s.value_counts())


14    19
13    18
17    17
10    16
19    16
15    14
12    14
16    14
11    11
18    11
Name: count, dtype: int64


In [94]:
string1 = "grand mere"
string2 = "ma danger"
s1 = pd.Series(list(string1))
s2 = pd.Series(list(string2))
print(s1[s1.isin(s2)])
lettre = "a"
a_times = s1[s1 == lettre]
a_times

0    g
1    r
2    a
3    n
4    d
5     
6    m
7    e
8    r
9    e
dtype: object


2    a
dtype: object